export interface BaseLanguageFilesDirectory {
    [key: string]: any;
}
export interface LanguageFilesDirectory extends BaseLanguageFilesDirectory {
    WinTotal: string;
    FreeSpins: string;
    FreeSpinsRemaining: string;
    FreeSpinsSmall: string;
    Logo: string;
    ResultAll: string;
    ResultPoint: string;
    ResultPointSmall: string;
    ResultWin: string;
    ResultTitle0: string;
    ResultTitle1: string;
    ResultTitle2: string;
    ResultTitle3: string;
    ResultTitle4: string;
    ResultTitle5: string;
    ResultTitle6: string;
    ResultTitle7: string;
    ResultTitle8: string;
    ResultTitle9: string;
    ResultTitle10: string;
    Type0: string;
    Type1: string;
    Type2: string;
    Type3: string;
    Type4: string;
    Type5: string;
    Type6: string;
    Type7: string;
    Type8: string;
    Type9: string;
    Type10: string;
    Type11: string;
    Type12: string;
    Type13: string;
    PickingSeats: string;
}

export const LanguageFiles: LanguageFilesDirectory = {
    // 共贏得
    WinTotal: 'tx_winTotal/spriteFrame',
    // 免費遊戲
    FreeSpins: 'tx_freeSpins/spriteFrame',
    // 剩餘免費次數
    FreeSpinsRemaining: 'tx_freeSpinsRemaining/spriteFrame',
    // 免費遊戲(小)
    FreeSpinsSmall: 'tx_freeSpins_small/spriteFrame',
    // Loading Logo
    Logo: 'tx_logo/spriteFrame',
    // 共
    ResultAll: 'tx_result_all/spriteFrame',
    // 台
    ResultPoint: 'tx_result_point/spriteFrame',
    // 台(小)
    ResultPointSmall: 'tx_result_point_small/spriteFrame',
    // 贏得分數
    ResultWin: 'tx_result_win/spriteFrame',
    // 天胡
    ResultTitle0: 'tx_result_title_0/spriteFrame',
    // 字一色
    ResultTitle1: 'tx_result_title_1/spriteFrame',
    // 大四喜
    ResultTitle2: 'tx_result_title_2/spriteFrame',
    // 地胡
    ResultTitle3: 'tx_result_title_3/spriteFrame',
    // 清一色
    ResultTitle4: 'tx_result_title_4/spriteFrame',
    // 大三元
    ResultTitle5: 'tx_result_title_5/spriteFrame',
    // 八仙過海
    ResultTitle6: 'tx_result_title_6/spriteFrame',
    // 湊一色
    ResultTitle7: 'tx_result_title_7/spriteFrame',
    // 碰碰胡
    ResultTitle8: 'tx_result_title_8/spriteFrame',
    // 花槓
    ResultTitle9: 'tx_result_title_9/spriteFrame',
    // 槓上開花
    ResultTitle10: 'tx_result_title_10/spriteFrame',
    // 天胡
    Type0: 'tx_type_0/spriteFrame',
    // 字一色
    Type1: 'tx_type_1/spriteFrame',
    // 大四喜
    Type2: 'tx_type_2/spriteFrame',
    // 地胡
    Type3: 'tx_type_3/spriteFrame',
    // 清一色
    Type4: 'tx_type_4/spriteFrame',
    // 大三元
    Type5: 'tx_type_5/spriteFrame',
    // 八仙過海
    Type6: 'tx_type_6/spriteFrame',
    // 湊一色
    Type7: 'tx_type_7/spriteFrame',
    // 碰碰胡
    Type8: 'tx_type_8/spriteFrame',
    // 花槓
    Type9: 'tx_type_9/spriteFrame',
    // 槓上開花
    Type10: 'tx_type_10/spriteFrame',
    // 花牌
    Type11: 'tx_type_11/spriteFrame',
    // 槓牌
    Type12: 'tx_type_12/spriteFrame',
    // 字牌
    Type13: 'tx_type_13/spriteFrame',
    // 抓位
    PickingSeats: 'tx_pickingSeats/spriteFrame',
};